runtime: nodejs
env: flex
# instance_class: F1
# automatic_scaling:
#   min_idle_instances: 1
#   max_idle_instances: automatic
#   min_pending_latency: automatic
#   max_pending_latency: automatic

# handlers:
#   - url: /record
#     # script: auto
#     # static_dir: static/images
#     http_headers:
#       Access-Control-Allow-Origin: "*"

manual_scaling:
  instances: 1

network:
  session_affinity: true
